# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '文章详细',
                'verbose_name_plural': '文章详细',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章名称')),
                ('summary', models.CharField(max_length=255, verbose_name='文章简介')),
                ('favour_count', models.IntegerField(default=0, verbose_name='被赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Articles', verbose_name='评论文章')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='modules.Comment', verbose_name='回复评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Favour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favour', models.BooleanField(default=False, verbose_name='是否已赞')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Articles', verbose_name='所赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='赞者')),
            ],
            options={
                'verbose_name': '赞',
                'verbose_name_plural': '赞',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=10, verbose_name='板块名称')),
            ],
            options={
                'verbose_name': '板块名称',
                'verbose_name_plural': '板块名称',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Modules', verbose_name='所属板块'),
        ),
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Articles', verbose_name='所属文章'),
        ),
    ]
